import { useEffect,useMemo,useRef,useState } from "react";
import { ArrowDown,ArrowUp,BarChart3,Check,ChevronRight,ChevronUp,Eye,EyeOff,FileText,List,Pencil,PieChart,RefreshCw,RotateCcw,SlidersHorizontal,X } from "lucide-react";
import { api } from "../api";
import type { StatisticsDetail,StatisticsResult } from "../types";
import { formatDateTime,STATUS_LABELS } from "../lib/task-utils";
import { statisticsComparisonRange,statisticsPresetRange,statisticsWeekdayLabel,type StatisticsPreset,type WeekStart } from "../lib/statistics-range";
import { buildReportPrompt,customReportTemplateIsValid,DEFAULT_CUSTOM_REPORT_TEMPLATE,REPORT_TEMPLATE_OPTIONS,type ReportTemplateMode } from "../lib/report-prompts";
import { DEFAULT_STATISTICS_CHART_ORDER,moveStatisticsChart,normalizeHiddenStatisticsCharts,normalizeStatisticsChartOrder,normalizeTaskTypeChartMode,STATISTICS_CHARTS,type StatisticsChartId,type TaskTypeChartMode } from "../lib/statistics-charts";

const localStart=(value:string)=>new Date(`${value}T00:00:00`).toISOString();
const nextLocalDay=(value:string)=>{const date=new Date(`${value}T00:00:00`);date.setDate(date.getDate()+1);return date.toISOString();};
const REPORT_MODE_KEY="in-line-report-template-mode";
const REPORT_CUSTOM_KEY="in-line-report-custom-template";
const REPORT_CONFIRMED_VERSION_KEY="in-line-report-template-confirmed-version";
const CHART_ORDER_KEY="in-line-statistics-chart-order";
const CHART_HIDDEN_KEY="in-line-statistics-chart-hidden";
const TASK_TYPE_MODE_KEY="in-line-statistics-task-type-mode";
const PIE_COLORS=["#0b3a82","#2f69a8","#55a0a6","#78a85a","#c68a16","#ce6b54","#7d68a8","#7890aa"];
const validMode=(value:string|null):value is ReportTemplateMode=>REPORT_TEMPLATE_OPTIONS.some(option=>option.value===value);
const comparisonName=(preset:StatisticsPreset)=>preset==="currentWeek"?"上周同期":preset==="previousWeek"?"上上周":preset==="month"?"再上一个月":preset==="quarter"?"再上一季度":"前一等长周期";
const deltaText=(current:number,previous:number)=>previous===0?(current===0?"持平":"新增"): `${current>=previous?"+":""}${Math.round((current-previous)/previous*100)}%`;
const changeTone=(current:number,previous:number)=>current>previous?"increase":current<previous?"decrease":"unchanged";

export default function StatisticsPanel({onOpenTask,notify,refreshKey=0,weekStartsOn}:{onOpenTask:(id:number)=>void;notify:(text:string)=>void;refreshKey?:string|number;weekStartsOn:WeekStart}){
  const [preset,setPreset]=useState<StatisticsPreset>("currentWeek");const initial=statisticsPresetRange("currentWeek",weekStartsOn);
  const [customStart,setCustomStart]=useState(initial.start);const [customEnd,setCustomEnd]=useState(initial.end);
  const [data,setData]=useState<StatisticsResult|null>(null);const [comparisonData,setComparisonData]=useState<StatisticsResult|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState("");
  const [selectedType,setSelectedType]=useState("");const [details,setDetails]=useState<StatisticsDetail[]>([]);const detailsRequestRef=useRef(0);
  const storedMode=window.localStorage.getItem(REPORT_MODE_KEY);
  const [reportMode,setReportMode]=useState<ReportTemplateMode>(validMode(storedMode)?storedMode:"review");
  const [customTemplate,setCustomTemplate]=useState(()=>window.localStorage.getItem(REPORT_CUSTOM_KEY)??DEFAULT_CUSTOM_REPORT_TEMPLATE);
  const [reportBusy,setReportBusy]=useState(false);const [chooserOpen,setChooserOpen]=useState(false);const [chooserMode,setChooserMode]=useState<ReportTemplateMode>("review");
  const [customEditorOpen,setCustomEditorOpen]=useState(false);const [customDraft,setCustomDraft]=useState(customTemplate);const [pendingGenerate,setPendingGenerate]=useState(false);const [pendingVersion,setPendingVersion]=useState("");
  const [chartManagerOpen,setChartManagerOpen]=useState(false);
  const [chartOrder,setChartOrder]=useState<StatisticsChartId[]>(()=>normalizeStatisticsChartOrder(window.localStorage.getItem(CHART_ORDER_KEY)));
  const [hiddenCharts,setHiddenCharts]=useState<StatisticsChartId[]>(()=>normalizeHiddenStatisticsCharts(window.localStorage.getItem(CHART_HIDDEN_KEY)));
  const [taskTypeMode,setTaskTypeMode]=useState<TaskTypeChartMode>(()=>normalizeTaskTypeChartMode(window.localStorage.getItem(TASK_TYPE_MODE_KEY)));
  const range=useMemo(()=>preset==="custom"?{start:customStart,end:customEnd}:statisticsPresetRange(preset,weekStartsOn),[preset,customStart,customEnd,weekStartsOn]);
  const comparisonRange=useMemo(()=>statisticsComparisonRange(preset,range),[preset,range.start,range.end]);
  const load=async()=>{if(!range.start||!range.end||range.start>range.end){setError("开始日期不能晚于结束日期");setLoading(false);return;}detailsRequestRef.current+=1;setLoading(true);setError("");setSelectedType("");setDetails([]);try{const [current,comparison]=await Promise.all([api.getStatistics(localStart(range.start),nextLocalDay(range.end)),api.getStatistics(localStart(comparisonRange.start),nextLocalDay(comparisonRange.end))]);setData(current);setComparisonData(comparison);}catch(value){setError(value instanceof Error?value.message:String(value));}finally{setLoading(false);}};
  useEffect(()=>{void load();},[range.start,range.end,comparisonRange.start,comparisonRange.end,refreshKey]);
  useEffect(()=>{if(!chooserOpen&&!customEditorOpen&&!chartManagerOpen)return;const close=(event:KeyboardEvent)=>{if(event.key!=="Escape")return;setChooserOpen(false);setCustomEditorOpen(false);setChartManagerOpen(false);setPendingGenerate(false);};window.addEventListener("keydown",close);return()=>window.removeEventListener("keydown",close);},[chooserOpen,customEditorOpen,chartManagerOpen]);
  const closeTypeDetails=()=>{detailsRequestRef.current+=1;setSelectedType("");setDetails([]);};
  const openType=async(taskType:string)=>{if(selectedType===taskType){closeTypeDetails();return;}const requestId=++detailsRequestRef.current;try{const values=await api.getStatisticsDetails(localStart(range.start),nextLocalDay(range.end),taskType);if(requestId!==detailsRequestRef.current)return;setDetails(values);setSelectedType(taskType);}catch(value){if(requestId===detailsRequestRef.current)setError(value instanceof Error?value.message:String(value));}};
  const persistChartOrder=(order:StatisticsChartId[])=>{setChartOrder(order);window.localStorage.setItem(CHART_ORDER_KEY,JSON.stringify(order));};
  const moveChart=(id:StatisticsChartId,direction:-1|1)=>persistChartOrder(moveStatisticsChart(chartOrder,id,direction));
  const toggleChart=(id:StatisticsChartId)=>{const hiding=!hiddenCharts.includes(id);const next=hiding?[...hiddenCharts,id]:hiddenCharts.filter(value=>value!==id);if(hiding&&id==="taskType")closeTypeDetails();setHiddenCharts(next);window.localStorage.setItem(CHART_HIDDEN_KEY,JSON.stringify(next));};
  const resetCharts=()=>{persistChartOrder(DEFAULT_STATISTICS_CHART_ORDER);setHiddenCharts([]);window.localStorage.removeItem(CHART_HIDDEN_KEY);notify("图表布局已恢复默认");};
  const changeTaskTypeMode=(mode:TaskTypeChartMode)=>{setTaskTypeMode(mode);window.localStorage.setItem(TASK_TYPE_MODE_KEY,mode);};
  const persistMode=(mode:ReportTemplateMode)=>{setReportMode(mode);window.localStorage.setItem(REPORT_MODE_KEY,mode);};
  const copyReportPrompt=async(mode:ReportTemplateMode,custom=customTemplate)=>{
    setReportBusy(true);
    try{await api.copyText(buildReportPrompt({mode,preset,start:range.start,end:range.end,customTemplate:custom}));notify("报告指令已复制，可直接粘贴到 AI 工具");}
    catch(value){notify("复制报告指令失败："+String(value));}
    finally{setReportBusy(false);}
  };
  const startGeneration=async()=>{
    if(!range.start||!range.end||range.start>range.end){notify("请先选择有效的统计时间范围");return;}
    const version=await api.getVersion().catch(()=>"unknown");
    if(window.localStorage.getItem(REPORT_CONFIRMED_VERSION_KEY)!==version){setChooserMode("review");setPendingVersion(version);setPendingGenerate(true);setChooserOpen(true);return;}
    await copyReportPrompt(reportMode);
  };
  const confirmChooser=async()=>{
    setChooserOpen(false);
    if(chooserMode==="custom"){setCustomDraft(customTemplate);setCustomEditorOpen(true);return;}
    persistMode(chooserMode);window.localStorage.setItem(REPORT_CONFIRMED_VERSION_KEY,pendingVersion);setPendingGenerate(false);await copyReportPrompt(chooserMode);
  };
  const saveCustomTemplate=async()=>{
    if(!customReportTemplateIsValid(customDraft)){notify("自定义模板必须保留报告类型、开始日期和结束日期三个占位符");return;}
    setCustomTemplate(customDraft);window.localStorage.setItem(REPORT_CUSTOM_KEY,customDraft);persistMode("custom");setCustomEditorOpen(false);
    if(pendingGenerate){window.localStorage.setItem(REPORT_CONFIRMED_VERSION_KEY,pendingVersion);setPendingGenerate(false);await copyReportPrompt("custom",customDraft);}
    else notify("自定义报告模板已保存");
  };
  const changeReportMode=(mode:ReportTemplateMode)=>{persistMode(mode);if(mode==="custom"){setCustomDraft(customTemplate);setPendingGenerate(false);setCustomEditorOpen(true);}};
  const maxTrend=Math.max(1,...(data?.trend.map(point=>point.handledTasks)??[1]));
  const processingRate=data?.summary.rateMode==="processing";
  const workloadRows=data&&comparisonData?[{label:"处理事项",current:data.summary.handledTasks,previous:comparisonData.summary.handledTasks},{label:"已完成",current:data.summary.completed,previous:comparisonData.summary.completed},{label:"待跟进",current:data.summary.handledTasks-data.summary.completed,previous:comparisonData.summary.handledTasks-comparisonData.summary.completed}]:[];
  const workloadMax=Math.max(1,...workloadRows.flatMap(item=>[item.current,item.previous]));
  const departmentRows=useMemo(()=>{if(!data||!comparisonData)return[];const names=new Set([...data.byDepartment.map(item=>item.department),...comparisonData.byDepartment.map(item=>item.department)]);return [...names].map(department=>({department,current:data.byDepartment.find(item=>item.department===department)?.handledTasks??0,previous:comparisonData.byDepartment.find(item=>item.department===department)?.handledTasks??0})).sort((left,right)=>Math.max(right.current,right.previous)-Math.max(left.current,left.previous)||left.department.localeCompare(right.department,"zh-CN"));},[data,comparisonData]);
  const departmentMax=Math.max(1,...departmentRows.flatMap(item=>[item.current,item.previous]));
  const taskTypeTotal=data?.byTaskType.reduce((total,item)=>total+item.handledTasks,0)??0;
  let pieCursor=0;
  const taskTypePie=(data?.byTaskType??[]).map((item,index)=>{const start=taskTypeTotal?pieCursor/taskTypeTotal*100:0;pieCursor+=item.handledTasks;const end=taskTypeTotal?pieCursor/taskTypeTotal*100:0;return{...item,start,end,color:PIE_COLORS[index%PIE_COLORS.length],share:taskTypeTotal?Math.round(item.handledTasks/taskTypeTotal*100):0};});
  const pieBackground=taskTypePie.length?`conic-gradient(${taskTypePie.map(item=>`${item.color} ${item.start}% ${item.end}%`).join(",")})`:"#e7edf4";
  const directionLegend=<span className="comparison-direction-legend"><i className="increase"/>红色为增长<i className="decrease"/>绿色为减少</span>;
  const renderChart=(id:StatisticsChartId)=>{
    if(!data)return null;
    if(id==="workload")return <section key={id} className="stat-card comparison-card chart-card"><div className="section-heading"><div><h2>周期工作量对比</h2><small>当前周期与{comparisonName(preset)} · 仅统计数量</small></div><div className="comparison-legend"><span className="current">当前</span><span className="previous">{comparisonName(preset)}</span></div></div><div className="comparison-range-note"><span>对比范围：{comparisonRange.start} 至 {comparisonRange.end}</span>{directionLegend}</div><div className="workload-comparison">{workloadRows.map(item=><div className="comparison-row" key={item.label}><div className="comparison-label"><strong>{item.label}</strong><span className={changeTone(item.current,item.previous)}>{deltaText(item.current,item.previous)}</span></div><div className="comparison-bars"><div><span className="current-bar" style={{width:`${item.current/workloadMax*100}%`}}/><b className={changeTone(item.current,item.previous)} title={`本周期较${comparisonName(preset)}${item.current>item.previous?"增长":item.current<item.previous?"减少":"持平"}`}>{item.current}</b></div><div><span className="previous-bar" style={{width:`${item.previous/workloadMax*100}%`}}/><b>{item.previous}</b></div></div></div>)}</div></section>;
    if(id==="department")return <section key={id} className="stat-card comparison-card chart-card"><div className="section-heading"><div><h2>部门 / 团队相关工作量</h2><small>按事项当前归属拆分 · 仅统计数量</small></div><div className="comparison-legend"><span className="current">当前</span><span className="previous">{comparisonName(preset)}</span></div></div><div className="comparison-direction-row">{directionLegend}</div>{departmentRows.length?<div className="department-comparison">{departmentRows.map(item=><div className="department-row" key={item.department}><div className="comparison-label"><strong title={item.department}>{item.department}</strong><span className={changeTone(item.current,item.previous)}>{deltaText(item.current,item.previous)}</span></div><div className="comparison-bars"><div><span className="current-bar" style={{width:`${item.current/departmentMax*100}%`}}/><b className={changeTone(item.current,item.previous)} title={`本周期较${comparisonName(preset)}${item.current>item.previous?"增长":item.current<item.previous?"减少":"持平"}`}>{item.current}</b></div><div><span className="previous-bar" style={{width:`${item.previous/departmentMax*100}%`}}/><b>{item.previous}</b></div></div></div>)}</div>:<p className="empty-copy">当前及对比周期均无部门相关工作量。</p>}<p className="comparison-note">同一事项归属多个部门时，会分别计入各部门，因此部门合计可能高于总事项数。</p></section>;
    if(id==="taskType")return <section key={id} className="stat-card chart-card task-type-card"><div className="section-heading"><div><h2>事项类型分布</h2><small>点击类型查看当前周期明细</small></div><div className="chart-mode-toggle" role="group" aria-label="事项类型图表形式"><button type="button" className={taskTypeMode==="list"?"active":""} onClick={()=>changeTaskTypeMode("list")} title="列表"><List size={15}/></button><button type="button" className={taskTypeMode==="pie"?"active":""} onClick={()=>changeTaskTypeMode("pie")} title="饼状图"><PieChart size={15}/></button></div></div>{data.byTaskType.length?(taskTypeMode==="list"?<div className="type-stats">{data.byTaskType.map(item=><button key={item.taskType} className={selectedType===item.taskType?"active":""} onClick={()=>void openType(item.taskType)}><span><strong>{item.taskType}</strong><small>已完成 {item.completed} · 待跟进 {item.pendingFollowUp}</small></span><b>{item.handledTasks}</b>{selectedType===item.taskType?<ChevronUp size={17}/>:<ChevronRight size={17}/>}</button>)}</div>:<div className="task-type-pie-layout"><div className="task-type-pie" style={{background:pieBackground}} role="img" aria-label={`事项类型饼状图，共 ${taskTypeTotal} 项`}><div><strong>{taskTypeTotal}</strong><span>处理事项</span></div></div><div className="task-type-pie-legend">{taskTypePie.map(item=><button type="button" key={item.taskType} className={selectedType===item.taskType?"active":""} onClick={()=>void openType(item.taskType)}><i style={{backgroundColor:item.color}}/><span><strong>{item.taskType}</strong><small>完成 {item.completed} · 待跟进 {item.pendingFollowUp}</small></span><b>{item.handledTasks}<small>{item.share}%</small></b>{selectedType===item.taskType?<ChevronUp size={16}/>:<ChevronRight size={16}/>}</button>)}</div></div>):<p className="empty-copy">当前周期没有有效处理事项。</p>}</section>;
    return <section key={id} className="stat-card trend-card chart-card"><div className="section-heading"><div><h2>工作量趋势</h2><small>{data.trendGranularity==="day"?"按日去重":"按自然周去重"}</small></div></div>{data.trend.length?<div className="trend-chart">{data.trend.map(point=><div className="trend-column" key={point.periodStart} title={`${point.periodStart}（${statisticsWeekdayLabel(point.periodStart)}）：${point.handledTasks} 项`}><b>{point.handledTasks}</b><span style={{height:point.handledTasks?`${Math.max(6,point.handledTasks/maxTrend*100)}%`:"8px"}}/><small><span>{statisticsWeekdayLabel(point.periodStart)}</span><time dateTime={point.periodStart}>{point.periodStart.slice(5)}</time></small></div>)}</div>:<p className="empty-copy">暂无趋势数据。</p>}<p className="trend-note">趋势数据按每日或每周分别去重；同一事项可能在不同日期或不同周重复出现。顶部总数在整个查询周期内统一去重。</p></section>;
  };
  return <section className="statistics-panel">
    <header className="statistics-header"><div><p>实际处理事项 · 周期内按事项去重</p><h1>统计中心</h1></div><div className="period-controls"><div className="preset-tabs">{(["currentWeek","previousWeek","month","quarter","custom"] as StatisticsPreset[]).map(value=><button className={preset===value?"active":""} key={value} onClick={()=>setPreset(value)}>{value==="currentWeek"?"本周":value==="previousWeek"?"上一周":value==="month"?"上一个月":value==="quarter"?"上一季度":"自定义"}</button>)}</div>{preset==="custom"&&<div className="custom-range"><input type="date" value={customStart} onChange={e=>setCustomStart(e.target.value)}/><span>至</span><input type="date" value={customEnd} onChange={e=>setCustomEnd(e.target.value)}/></div>}<div className="period-footer"><small>{range.start} 至 {range.end}{preset==="currentWeek"&&` · ${weekStartsOn==="monday"?"周一":"周日"}起算`}</small><div className="report-controls"><label><span>报告结构</span><select value={reportMode} onChange={event=>changeReportMode(event.target.value as ReportTemplateMode)}>{REPORT_TEMPLATE_OPTIONS.map(option=><option key={option.value} value={option.value}>{option.label}</option>)}</select></label>{reportMode==="custom"&&<button type="button" className="button secondary report-edit-button" onClick={()=>{setCustomDraft(customTemplate);setPendingGenerate(false);setCustomEditorOpen(true);}}><Pencil size={14}/>编辑</button>}<button type="button" className="button primary report-copy-button" disabled={reportBusy||!range.start||!range.end||range.start>range.end} onClick={()=>void startGeneration()}><FileText size={15}/>{reportBusy?"正在生成…":"生成报告"}</button></div></div></div></header>
    {error&&<div className="statistics-error"><span>{error}</span><button onClick={()=>void load()}><RefreshCw size={15}/>重新加载</button></div>}
    {loading?<div className="statistics-loading"><BarChart3 size={32}/><p>正在汇总处理活动…</p></div>:data&&<>
      <div className="summary-grid">
        <article><span>处理事项总数</span><strong>{data.summary.handledTasks}</strong></article><article><span>已处理</span><strong>{data.summary.processed}</strong></article><article><span>已完成</span><strong>{data.summary.completed}</strong></article><article><span>待补充材料</span><strong>{data.summary.waitingMaterials}</strong></article><article><span>待内部确认</span><strong>{data.summary.waitingConfirmation}</strong></article><article><span>待对方确认</span><strong>{data.summary.waitingCounterpartyConfirmation}</strong></article><article className="rate-card"><span>{processingRate?"有效处理率":"事项办结率"}</span><strong>{Math.round(data.summary.completionRate*100)}%</strong><small>{processingRate?`有效办理 ${data.summary.rateNumerator} ÷ 应处理 ${data.summary.rateDenominator}`:`已完成 ${data.summary.rateNumerator} ÷ 实际处理 ${data.summary.rateDenominator}`}</small></article>
      </div>
      <div className="chart-management-bar"><div><strong>统计图表</strong><span>按你的工作习惯排列，只显示需要关注的内容</span></div><button type="button" className="button secondary" onClick={()=>setChartManagerOpen(true)}><SlidersHorizontal size={15}/>管理图表</button></div>
      {chartOrder.some(id=>!hiddenCharts.includes(id))?<div className="statistics-charts-grid">{chartOrder.filter(id=>!hiddenCharts.includes(id)).map(renderChart)}</div>:<div className="charts-empty"><EyeOff size={24}/><div><strong>所有图表均已隐藏</strong><span>在“管理图表”中重新开启需要的图表。</span></div><button className="button secondary" onClick={()=>setChartManagerOpen(true)}>管理图表</button></div>}
      {selectedType&&<section className="stat-card details-card"><div className="section-heading"><div><h2>{selectedType} · 事项明细</h2><small>同一事项仅显示一行</small></div><div className="details-heading-actions"><b>{details.length} 项</b><button type="button" className="button secondary small" onClick={closeTypeDetails}><ChevronUp size={15}/>收起明细</button></div></div><div className="statistics-table-wrap"><table className="statistics-table"><thead><tr><th>事项编号</th><th>事项标题</th><th>部门 / 团队</th><th>对接人</th><th>最终结果</th><th>首次处理</th><th>最后处理</th><th>次数</th></tr></thead><tbody>{details.map(item=><tr key={item.taskId} onClick={()=>onOpenTask(item.taskId)}><td>{item.permanentNumber}</td><td><strong>{item.title}</strong></td><td>{item.department}</td><td>{item.contact}</td><td>{STATUS_LABELS[item.resultStatus]}</td><td>{formatDateTime(item.firstHandledAt)}</td><td>{formatDateTime(item.lastHandledAt)}</td><td>{item.handlingCount}</td></tr>)}</tbody></table></div></section>}
    </>}
    {chartManagerOpen&&<div className="modal-layer nested-modal" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)setChartManagerOpen(false);}}><section className="chart-manager-dialog" role="dialog" aria-modal="true" aria-labelledby="chart-manager-title"><header><div><span>统计工作台</span><h2 id="chart-manager-title">管理图表</h2></div><button className="icon-button" onClick={()=>setChartManagerOpen(false)} aria-label="关闭"><X size={18}/></button></header><p>使用上下按钮调整显示顺序；隐藏图表不会删除数据，随时可以重新显示。</p><div className="chart-manager-list">{chartOrder.map((id,index)=>{const chart=STATISTICS_CHARTS.find(item=>item.id===id)!;const hidden=hiddenCharts.includes(id);return <article key={id} className={hidden?"hidden":""}><span className="chart-order-number">{String(index+1).padStart(2,"0")}</span><div><strong>{chart.label}</strong><small>{chart.description}</small></div><div className="chart-order-actions"><button type="button" className="icon-button" disabled={index===0} onClick={()=>moveChart(id,-1)} title="上移" aria-label={`上移 ${chart.label}`}><ArrowUp size={16}/></button><button type="button" className="icon-button" disabled={index===chartOrder.length-1} onClick={()=>moveChart(id,1)} title="下移" aria-label={`下移 ${chart.label}`}><ArrowDown size={16}/></button><button type="button" className={`chart-visibility-button ${hidden?"":"visible"}`} onClick={()=>toggleChart(id)}>{hidden?<><EyeOff size={15}/>已隐藏</>:<><Eye size={15}/>显示中</>}</button></div></article>;})}</div><footer><button className="button secondary" onClick={resetCharts}><RotateCcw size={15}/>恢复默认</button><button className="button primary" onClick={()=>setChartManagerOpen(false)}>完成</button></footer></section></div>}
    {chooserOpen&&<div className="modal-layer nested-modal" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget){setChooserOpen(false);setPendingGenerate(false);}}}><section className="report-template-dialog" role="dialog" aria-modal="true" aria-labelledby="report-template-title"><header><div><span>首次生成报告</span><h2 id="report-template-title">选择报告结构</h2></div><button className="icon-button" onClick={()=>{setChooserOpen(false);setPendingGenerate(false);}} aria-label="关闭"><X size={18}/></button></header><p className="report-mcp-notice">生成报告前，请先在“软件设置 → AI MCP 接入”中复制通用接入信息，并让当前 AI 工具完成 MCP 配置。</p><div className="report-template-options">{REPORT_TEMPLATE_OPTIONS.map(option=><button type="button" key={option.value} className={chooserMode===option.value?"active":""} onClick={()=>setChooserMode(option.value)}><span>{chooserMode===option.value&&<Check size={15}/>}</span><strong>{option.label}</strong><small>{option.description}</small></button>)}</div><footer><button className="button secondary" onClick={()=>{setChooserOpen(false);setPendingGenerate(false);}}>取消</button><button className="button primary" onClick={()=>void confirmChooser()}>{chooserMode==="custom"?"编辑模板":"确认并生成"}</button></footer></section></div>}
    {customEditorOpen&&<div className="modal-layer nested-modal" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget){setCustomEditorOpen(false);setPendingGenerate(false);}}}><section className="report-custom-dialog" role="dialog" aria-modal="true" aria-labelledby="report-custom-title"><header><div><span>自定义报告结构</span><h2 id="report-custom-title">编辑指令模板</h2></div><button className="icon-button" onClick={()=>{setCustomEditorOpen(false);setPendingGenerate(false);}} aria-label="关闭"><X size={18}/></button></header><div className="report-custom-body"><p>软件只替换报告类型和日期，占位符必须保留；其他内容将完全按你的模板复制。</p><textarea value={customDraft} onChange={event=>setCustomDraft(event.target.value)} aria-label="自定义报告指令模板"/><small>必须保留：{`{{报告类型}}`}、{`{{开始日期}}`}、{`{{结束日期}}`}</small></div><footer><button className="button secondary" onClick={()=>{setCustomEditorOpen(false);setPendingGenerate(false);}}>取消</button><button className="button primary" onClick={()=>void saveCustomTemplate()}>{pendingGenerate?"保存并生成":"保存模板"}</button></footer></section></div>}
  </section>;
}
